export const useCasePageData = [
  {
    title: "At Home",
    description: [
      "Sometimes, the day feels too loud.",
      "Deadlines. Notifications. Thoughts that won’t slow down.",
      "Sap Symphony doesn’t ask you to meditate.It simply creates a space where slowing down becomes natural.",
      "In a living room.In a reading corner.Beside your favourite plant.",
      "Not as background music but as something alive, responding quietly with you.",
    ],
    image: "/use-case/1.webp",
  },
  {
    title: "In Wellness Spaces",
    description: [
      "Yoga studios don’t need more sound.",
      "They need the right sound.",
      "Sap Symphony replaces static playlists with something real a soundscape shaped by life itself.",
      "Each session becomes slightly different.Each moment becomes present.",
      "Because the music isn’t repeated.",
      "It unfolds.",
    ],
    image: "/use-case/2.webp",
    flexReverse: true,
  },
  {
    title: "In Healthcare",
    description: [
      "Hospitals are full of waiting.",
      "Waiting for reports.Waiting for answers.Waiting for peace.",
      "Sap Symphony introduces a subtle presence into these spaces a living calm that reduces tension without saying a word.",
      "Not therapy in the clinical sense.",
      "But comfort in the human sense.",
    ],
    image: "/use-case/3.webp",
  },
  {
    title: "In Workplaces",
    description: [
      "Work doesn’t have to feel mechanical.",
      "Imagine a workspace that breathes.",
      "Sap Symphony creates an environment that gently reduces stresswithout interrupting productivity.",
      "It doesn’t distract.",
      "It settles.",
      "Turning offices from pressure zonesinto creative zones.",
    ],
    image: "/use-case/3.webp",
    flexReverse: true,
  },
  {
    title: "In Therapy & Recovery",
    description: [
      "Some healing cannot be rushed.",
      "Sap Symphony supports environments designed for rest, recovery, and emotional reset.",
      "Sleep spaces.Stress relief rooms.Rehabilitation environments.",
      "Where silence feels heavy Sap Symphony makes it supportive.",
    ],
    image: "/use-case/4.webp",
  },
  {
    title: "In Elder Care",
    description: [
      "Loneliness often arrives quietly.",
      "Sap Symphony brings presence without intrusion.",
      "For seniors, it becomes:",
      "• A companion",
      "• A calming rhythm",
      "• A gentle connection to life",
      "Not technology that demands attention.",
      "But something that simply exists with them.",
    ],
    image: "/use-case/3.webp",
    flexReverse: true,
  },
  {
    title: "In Therapy & Recovery",
    description: [
      "Sometimes calm needs to be shared.",
      "Sap Symphony fits into:",
      "• Retreat centres",
      "• Resorts",
      "• Public wellness programs",
      "• Community spaces",
      "Helping people reconnect, not just with themselves, but with the living world around them.",
    ],
    image: "/use-case/5.webp",
  },
  {
    title: "The Truth Is…",
    description: ["Sap Symphony doesn’t belong in a category.",
      "It belongs wherever people are:",
      "• Trying to slow down",
      "• Trying to breathe",
      "• Trying to feel better",
      "Without forcing it.",
    ],
    image: "/use-case/6.webp",
    flexReverse: true,
  },
];
